version: '3.8'

networks:
  lab-network:
    driver: bridge

services:
  auth-service:
    build:
      context: auth-service
    #container_name: auth-service
    environment:
      - JWT_SIGNING_SECRET=MySuperSecretSigningKeyForPhase3ContainerizedLearningLab
    networks:
      - lab-network

  order-service:
    build:
      context: order-service
    #container_name: order-service
    environment:
      - JWT_SIGNING_SECRET=MySuperSecretSigningKeyForPhase3ContainerizedLearningLab
    networks:
      - lab-network

  inventory-service:
    build:
      context: inventory-service
    #container_name: inventory-service
    environment:
      - JWT_SIGNING_SECRET=MySuperSecretSigningKeyForPhase3ContainerizedLearningLab 
    networks:
      - lab-network

  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    ports:
      - "8000:8000" # Expose the Nginx entryway out to your physical host machine
    volumes:
      - ./nginx-dnsCache.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - order-service
      - inventory-service
    networks:
      - lab-network