
    resolver 127.0.0.11 ipv6=off valid=60s;

    #Define a custom log format that exposes the target container's destination IP
    log_format microservices_layout '$remote_addr - $remote_user [$time_local] '
                    '"$request" $status $body_bytes_sent '
                    'to: $upstream_addr status: $upstream_status';

    server {
        listen 8000;
        server_name localhost;
        
        #Force this server block to use our new descriptive log layout
        access_log /var/log/nginx/access.log microservices_layout;

        location /inventory/ {
            set $inventory_target "inventory-service";
            proxy_pass http://$inventory_target:8080;
        }
        
        location /orders {
            set $order_target "order-service";
            proxy_pass http://$order_target:8080;
        }

        location /auth/ {
            set $auth_target "auth-service";
            proxy_pass http://$auth_target:8080;
        }
    }
