server.port=8082
spring.application.name=order-service

# ? PAIN POINT: We must copy-paste this identical key from auth-service.
# If this key slips out of sync, order-service will reject completely valid tokens.
jwt.secret=MySuperSecretSigningKeyForPhase1ContainerizedLearningLab
inventory.service.url=http://localhost:8081/inventory